### ISSUE TITLE
Internal Questions about Design System

### ISSUE THREAD

**Issue by Chaparroa** [LACMTA/design-system#3]
1. Where will the digital design system live?

Ideally, GitHub.

2. What is the foundation we're starting with for the front-end DS?
3. How will the DS connect to metro.net WP site? Short-term and Long-term
4. How will it account for design studio and signage
5. Regular review for ADA WCAG compliance 
6. Use starting UI Kit pieces to test out workflow. metro.net Homepage, Fares Overview, Fares LIFE, metro.net main navigation & dropdown
7. Determine workflow of new pieces and updates to existing pieces
8. Determine Design System Goals

**Comment by matikin9** [comment]
Addressing these questions via the Action Group(s)
